access.go
access_test.go
length.go

add New bool object and length function

add New bool and length function

---

unmarshal.go
unmarshal_test.go

修正：jsonDict unmarshal interface只能unmarshal serializable interface

fix: jsonDict cannot unmarshal any interface but serializable interface

---

access.go
access_test.go
clone.go
clone_test.go
compond.go
currency.go
currency_test.go
dict.go
doc.go
equals.go
interface.go
interface_test.go
iszero.go
jsonutils.go
jsonutils_test.go
length.go
marshal.go
marshal_test.go
querystring.go
querystring_test.go
reflect.go
size.go
unmarshal.go
unmarshal_test.go
update.go
update_test.go
utils.go
utils_test.go
yamlutils.go
yamlutils_test.go

add copyright header

---

access.go
errors.go
jsonutils.go
querystring.go
reflect.go
unmarshal.go
utils.go
yamlutils.go

fix: use github.com/pkg/errors

---

querystring.go
utils.go

fix: jsonutils ignore nil pointers

---

utils.go

add GetAnyString2 to return key of string

fix: add GetAnyString2 to return key of string

---

utils.go

fix: add GetStringArray method

---

access.go
errors.go
jsonutils.go
querystring.go
querystring_test.go
reflect.go
stringsegment.go
stringsegment_test.go
unmarshal.go
utils.go

修正：数组在格式化为querystring 时候应该加上.0, .1的下标
/cc @zexi @yousong @ioito

fix: querystring format jsonarray

---

unmarshal.go

```
unmarshal: fix reporting ErrTypeMismatch
unmarshal: fix error reporting
```
/cc @swordqiu

unmarshal: fix error reporting

---

access.go

fix endless loop on get array at jsondict with jsondict

---

unmarshal.go
unmarshal_test.go

field has been deprecated by another field. Also, if a struct has
"AfterUnmashal" method, the method will called after each unmarshal
operation.
1. 给struct field增加了deprecateby的tag，用来指明该field被哪个别的字段deprecated
2. 当unmarshal完成后，如果数据有AfterUnmarshal的方法，则会自动调用该方法。
增加这两个方法用于数据结构的字段迁移。

feature: add deprecated-by tag for struct field, which indicating the

---

go.mod
go.sum

fix: update go.mod go.sum

---

unmarshal.go
unmarshal_test.go

jsonutils.Unmarshal调用struct的AfterUnmarshal方法需要处理嵌套匿名struct的情况
/cc @yousong @zexi

fix: jsonutils.Unmarshal should call struct's AfterUnmarshal recursively

---

consts.go
marshal.go
marshal_test.go
unmarshal.go

增加：marshal的时候也支持deprecated-by tag，marshal时候会将root field的值copy到deprecated的field中。
/cc @zexi @yousong @wanyaoqi

feature: marshal support deprecated-by tag

---

consts.go
marshal_test.go
unmarshal.go
unmarshal_test.go

修正：reflectutils的json名称匹配规则修改后的兼容性修改。同时把deprecated-by改为yunion:deprecated-by

fix: json field name match rule changes

---

currency.go
unmarshal.go
unmarshal_test.go

修正：unmarshal empty string到int字段导致unmarshal失败
/cc @zexi @yousong

fix: unmarshal empty string into number

---

values.go

修正：恢复删除的Value()方法
/cc @zexi @yousong

fix: recover Value()

---

go.mod
go.sum
jsonutils_test.go
unmarshal.go
unmarshal_test.go

修正：unmarshal *JSONDict逻辑不对，但把JSONDict的data从map切换成sortedmap后问题暴露出来了
/cc @yousong @wanyaoqi @zexi

fix: unmarshal *JSONDict fail after using sortedmap

---

string.go

* 更新json float string输出格式
/cc @swordqiu @yousong

update json float string output format

---

utils.go
utils_test.go

BUG: fix new time string with utc time zone

---

go.mod
go.sum
marshal_test.go
unmarshal_test.go

/cc @swordqiu 
/hold wait https://github.com/yunionio/pkg/pull/69 to merge

fix: TAG_PREFIX invalid syntax

---

access.go
access_test.go
clone_test.go
interface_test.go
jsonutils.go
marshal.go
string.go
string_test.go
unmarshal_test.go

- seprate float64 and float32
/cc @swordqiu @zexi @yousong

bugfix: seprate float64 and float32

---

unmarshal.go

time parse ignore err

---

access_test.go
jsonutils.go

修正：字符串包含特殊字符时encode的字符串decode失败

fix: fail to encode/decode strings ignore special chars

---

.circleci/config.yml
marshal.go
marshal_test.go

marshal: return null for nil ptr (inc. interface with  type)
/cc @zhaoxiangchun @swordqiu @zexi @rainzm

marshal: return null for nil ptr (inc. interface with  type)

---

jsonutils.go
unmarshal_test.go

fix: \r should be considered as a separator

fix: \r should be considered as a separator

---

unmarshal_test.go

fix: add test case for map string

---

clone.go

fix: DeepCopy add JSONValue case

---

marshal.go
std_json.go
std_json_test.go
unmarshal.go

feat: compatible with std unmarshal interface

---

Makefile
jsonpointer.go
jsonutils.go
marshal.go
marshal_session.go
marshal_test.go
parse_session.go
std_json.go
string.go
string_test.go
stringsegment_test.go
unmarshal.go
unmarshal_session.go
write.go

支持marshal/unmarshal带循环引用指针的结构体
参见TestMarshalLoop这个TestCase
/cc @zexi @wanyaoqi

feature: marshal pointer loop

---

jsonpointer.go
marshal.go

fix: nil pointer loop

---

json_pointer_trace.go
jsonpointer.go
marshal.go
marshal_session.go
marshal_test.go

只有在发现指针loop的情况下才使用node引用的方式编码json

fix: use json pointer when loop detected only!

---

.github/workflows/build-and-test.yaml
Makefile

fix: minor fixes

---

marshal_test.go
unmarshal.go
unmarshal_test.go

fix: unmarshal not initialize slice for zero length array

fix: unmarshal not initialize slice for zero length array

---

jsonutils.go

fix: generate swagger api

---

jsonutils.go
unmarshal_test.go

fix: json.ParseStream

---

errors.go
errors_test.go

fix: NewJSONError panic
